//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayQT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DmQT06Entities : DbContext
    {
        public DmQT06Entities()
            : base("name=DmQT06Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<CashBill> CashBill { get; set; }
        public virtual DbSet<CashBillDetail> CashBillDetail { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<InstallmentBill> InstallmentBill { get; set; }
        public virtual DbSet<InstallmentBillDetail> InstallmentBillDetail { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
